org.gradle.jvmargs=-Xmx1G

# Mod Metadata
mod_id=mubble
mod_name=Mubble
mod_logo=https://dawnteammc.github.io/mubble/images/logo.png
mod_color=15415081
loader_name=Fabric
loader_icon=https://fabricmc.net/assets/logo.png

# check these on https://fabricmc.net/versions.html
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.114.1+1.21.3

# https://maven.terraformersmc.com/releases/com/terraformersmc/biolith-fabric
biolith_version=3.4.0-alpha.4