org.gradle.jvmargs=-Xmx1G

# Mod Metadata
mod_id=mubble
mod_name=Mubble
mod_logo=https://dawnteammc.github.io/mubble/images/logo.png
mod_color=15415081
loader_name=Fabric
loader_icon=https://fabricmc.net/assets/logo.png

# check these on https://fabricmc.net/versions.html
minecraft_version=26.1-snapshot-2
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Fabric API
fabric_api_version=0.141.2+26.1

# https://maven.terraformersmc.com/releases/com/terraformersmc/biolith-fabric
biolith_version=3.5.0-beta.2