modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/Hugman76/Mubble/issues"

[[mods]]
modId="mubble"
version="1.4-pre4"
displayName="Mubble"
updateJSONURL="https://raw.githubusercontent.com/Hugman76/Mubble/master/update.json"
displayURL="https://minecraft.curseforge.com/projects/mubble"
logoFile="assets/mubble/textures/gui/logo.png"
credits="https://ftb.gamepedia.com/Mubble/Credits"
authors="Hugman_76"
description='''
Discover the Nintendo Universe and way more.
'''

[[dependencies.mubble]]
modId="forge"
mandatory=true
versionRange="[25,)"
ordering="NONE"
side="BOTH"

[[dependencies.mubble]]
modId="minecraft"
mandatory=true
versionRange="[1.13.2]"
ordering="NONE"
side="BOTH"