modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Hugman76/Mubble/issues"
logoFile="logo.png"

[[mods]]
modId="mubble"
version="1.4"
displayName="Mubble"
updateJSONURL="https://raw.githubusercontent.com/Hugman76/Mubble/1.14/update.json"
displayURL="https://sites.google.com/view/mubblemc"
credits="https://ftb.gamepedia.com/Mubble/Credits"
authors="Hugman_76"
description='''Discover the Nintendo Universe and way more.'''

[[dependencies.mubble]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.mubble]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"