modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Hugman76/Mubble/issues"
logoFile="logo.png"

[[mods]]
modId="mubble"
version="3.0.2"
displayName="Mubble"
updateJSONURL="https://raw.githubusercontent.com/Hugman76/Mubble/1.15/update.json"
displayURL="https://sites.google.com/view/mubblemc"
credits="https://ftb.gamepedia.com/Mubble/Credits"
authors="Hugman"
description='''
Mubble adds over 1 000 features to your world, including decorative blocks, costumes, biomes and way more.
This mod also features additions from the universes of Super Mario, Sonic, Celeste, Castlevania, Pokémon, Undertale and many other beloved licenses!
Visit the official website for more information.
'''

[[dependencies.mubble]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.mubble]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"