modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
displayName="Mubble"
modId="mubble"
version="1.3"
logoFile="assets/mubble/textures/gui/logo.png"
description='''
Discover the Nintendo Universe and way more.
'''
authors="Hugman_76"
credits="https://ftb.gamepedia.com/Mubble/Credits"

issueTrackerURL="https://github.com/Hugman76/Mubble/issues"
displayURL="https://minecraft.curseforge.com/projects/mubble"
updateJSONURL="https://raw.githubusercontent.com/Hugman76/Mubble/master/update.json"