modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Hugman76/Mubble/issues"
logoFile="logo.png"

[[mods]]
modId="mubble"
version="2.2"
displayName="Mubble"
updateJSONURL="https://raw.githubusercontent.com/Hugman76/Mubble/1.14/update.json"
displayURL="https://sites.google.com/view/mubblemc"
credits="https://ftb.gamepedia.com/Mubble/Credits"
authors="Hugman"
description='''
    Expand your world with features from the Nintendo universe, and way more.
    Mubble is a very complete mod that adds many useful blocks, items and costumes that feel very natural to Minecraft vanilla.

    This mod also includes a ton of content based around Nintendo (a lot of Super Mario Maker 2 content) and indie games such as Celeste and Castlevania.

    Please visit the Mubble website and pages on the FTB Wiki for more information.
'''

[[dependencies.mubble]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.mubble]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"