package hugman.mod.init;

import java.util.ArrayList;
import java.util.List;

import hugman.mod.objects.blocks.BlockBalloon;
import hugman.mod.objects.blocks.BlockBase;
import hugman.mod.objects.blocks.BlockBrick;
import hugman.mod.objects.blocks.BlockCloud;
import hugman.mod.objects.blocks.BlockCrops;
import hugman.mod.objects.blocks.BlockDirectional;
import hugman.mod.objects.blocks.BlockDirt;
import hugman.mod.objects.blocks.BlockEmpty;
import hugman.mod.objects.blocks.BlockFallingGlass;
import hugman.mod.objects.blocks.BlockFlower;
import hugman.mod.objects.blocks.BlockGrass;
import hugman.mod.objects.blocks.BlockGrassPlant;
import hugman.mod.objects.blocks.BlockHugeMushroom;
import hugman.mod.objects.blocks.BlockMushroom;
import hugman.mod.objects.blocks.BlockNote;
import hugman.mod.objects.blocks.BlockOre;
import hugman.mod.objects.blocks.BlockPillar;
import hugman.mod.objects.blocks.BlockPortal;
import hugman.mod.objects.blocks.BlockPuyo;
import hugman.mod.objects.blocks.BlockQuestion;
import hugman.mod.objects.blocks.BlockRotating;
import hugman.mod.objects.blocks.BlockStairs;
import hugman.mod.objects.blocks.BlockTetris;
import hugman.mod.objects.blocks.BlockUnstable;
import hugman.mod.objects.blocks.BlockWall;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;

/** 
 * Init class - used to initialize blocks.
 */
public class BlockInit
{
	public static final List<Block> BLOCKS = new ArrayList<Block>();
	
	public static final Block VANADIUM_BLOCK = new BlockBase("vanadium_block", CreativeTabs.BUILDING_BLOCKS, Material.IRON, 5f, 30f, SoundType.METAL);
	public static final Block VANADIUM_ORE = new BlockOre("vanadium_ore", CreativeTabs.BUILDING_BLOCKS);
	public static final Block RED_BRICKS = new BlockBase("red_bricks", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block RED_BRICK_STAIRS = new BlockStairs("red_brick", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block WHITE_BRICKS = new BlockBase("white_bricks", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block WHITE_BRICK_STAIRS = new BlockStairs("white_brick", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block BLUNITE = new BlockBase("blunite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block BLUNITE_STAIRS = new BlockStairs("blunite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block BLUNITE_WALL = new BlockWall("blunite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block POLISHED_BLUNITE = new BlockBase("polished_blunite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block POLISHED_BLUNITE_STAIRS = new BlockStairs("polished_blunite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block CARBONITE = new BlockBase("carbonite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block CARBONITE_STAIRS = new BlockStairs("carbonite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block CARBONITE_WALL = new BlockWall("carbonite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block POLISHED_CARBONITE = new BlockBase("polished_carbonite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block POLISHED_CARBONITE_STAIRS = new BlockStairs("polished_carbonite", CreativeTabs.BUILDING_BLOCKS, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block FOOTBLOCK = new BlockBase("footblock", CreativeTabs.DECORATIONS, Material.CLOTH, 0.8f, 4f, SoundType.CLOTH);
	public static final Block WHITE_CLOUD_BLOCK = new BlockCloud("white");
	public static final Block LIGHT_GRAY_CLOUD_BLOCK = new BlockCloud("light_gray");
	public static final Block GRAY_CLOUD_BLOCK = new BlockCloud("gray");
	public static final Block BLACK_CLOUD_BLOCK = new BlockCloud("black");
	public static final Block TOMATO = new BlockCrops("tomato", ItemInit.TOMATO);
	public static final Block SALAD = new BlockCrops("salad", ItemInit.SALAD);
	public static final Block CHEESE_BLOCK = new BlockBase("cheese_block", CreativeTabs.FOOD, Material.CLOTH, 0.5f, 2f, SoundType.SNOW);
	public static final Block UNSTABLE_STONE = new BlockUnstable("unstable_stone", CreativeTabs.TRANSPORTATION, Material.ROCK, 0.1f, 1f, SoundType.STONE);
	public static final Block ULTIMATUM_PORTAL = new BlockPortal("ultimatum", 64);
	public static final Block QUESTION_BLOCK = new BlockQuestion();
	public static final Block EMPTY_BLOCK = new BlockEmpty();
	public static final Block ROTATING_BLOCK = new BlockRotating();
	public static final Block LIGHT_BLOCK = new BlockBase("light_block", CreativeTabInit.SUPER_MARIO, Material.ROCK, 1.5f, 30f, SoundType.STONE, 15);
	public static final Block BRICK_BLOCK = new BlockBrick("brick_block", CreativeTabInit.SUPER_MARIO);
	public static final Block GOLDEN_BRICK_BLOCK = new BlockBrick("golden_brick_block", CreativeTabInit.SUPER_MARIO);
	public static final Block NOTE_BLOCK = new BlockNote("note_block", CreativeTabInit.SUPER_MARIO);
	public static final Block SUPER_NOTE_BLOCK = new BlockNote("super_note_block", CreativeTabInit.SUPER_MARIO);
	public static final Block FIRE_FLOWER = new BlockFlower("fire_flower", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block ICE_FLOWER = new BlockFlower("ice_flower", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block BOOMERANG_FLOWER = new BlockFlower("boomerang_flower", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block CLOUD_FLOWER = new BlockFlower("cloud_flower", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block GOLD_FLOWER = new BlockFlower("gold_flower", CreativeTabInit.SUPER_MARIO, 5);
	public static final Block BLUE_MUSHROOM = new BlockMushroom("blue", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block LIGHT_BLUE_MUSHROOM = new BlockMushroom("light_blue", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block CYAN_MUSHROOM = new BlockMushroom("cyan", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block GREEN_MUSHROOM = new BlockMushroom("green", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block LIME_MUSHROOM = new BlockMushroom("lime", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block YELLOW_MUSHROOM = new BlockMushroom("yellow", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block ORANGE_MUSHROOM = new BlockMushroom("orange", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block PINK_MUSHROOM = new BlockMushroom("pink", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block MAGENTA_MUSHROOM = new BlockMushroom("magenta", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block PURPLE_MUSHROOM = new BlockMushroom("purple", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block WHITE_MUSHROOM = new BlockMushroom("white", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block LIGHT_GRAY_MUSHROOM = new BlockMushroom("light_gray", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block GRAY_MUSHROOM = new BlockMushroom("gray", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block BLACK_MUSHROOM = new BlockMushroom("black", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block BLUE_MUSHROOM_BLOCK = new BlockHugeMushroom("blue", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block LIGHT_BLUE_MUSHROOM_BLOCK = new BlockHugeMushroom("light_blue", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block CYAN_MUSHROOM_BLOCK = new BlockHugeMushroom("cyan", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block GREEN_MUSHROOM_BLOCK = new BlockHugeMushroom("green", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block LIME_MUSHROOM_BLOCK = new BlockHugeMushroom("lime", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block YELLOW_MUSHROOM_BLOCK = new BlockHugeMushroom("yellow", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block ORANGE_MUSHROOM_BLOCK = new BlockHugeMushroom("orange", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block PINK_MUSHROOM_BLOCK = new BlockHugeMushroom("pink", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block MAGENTA_MUSHROOM_BLOCK = new BlockHugeMushroom("magenta", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block PURPLE_MUSHROOM_BLOCK = new BlockHugeMushroom("purple", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block WHITE_MUSHROOM_BLOCK = new BlockHugeMushroom("white", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block LIGHT_GRAY_MUSHROOM_BLOCK = new BlockHugeMushroom("light_gray", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block GRAY_MUSHROOM_BLOCK = new BlockHugeMushroom("gray", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block BLACK_MUSHROOM_BLOCK = new BlockHugeMushroom("black", CreativeTabInit.SUPER_MARIO, 0);
	public static final Block BLUE_TETRIS_BLOCK = new BlockTetris("blue", "block", Material.ROCK);
	public static final Block LIGHT_BLUE_TETRIS_BLOCK = new BlockTetris("light_blue", "block" ,Material.ROCK);
	public static final Block CYAN_TETRIS_BLOCK = new BlockTetris("cyan", "block", Material.ROCK);
	public static final Block GREEN_TETRIS_BLOCK = new BlockTetris("green", "block", Material.ROCK);
	public static final Block LIME_TETRIS_BLOCK = new BlockTetris("lime", "block", Material.ROCK);
	public static final Block YELLOW_TETRIS_BLOCK = new BlockTetris("yellow", "block", Material.ROCK);
	public static final Block ORANGE_TETRIS_BLOCK = new BlockTetris("orange", "block", Material.ROCK);
	public static final Block RED_TETRIS_BLOCK = new BlockTetris("red", "block", Material.ROCK);
	public static final Block PINK_TETRIS_BLOCK = new BlockTetris("pink", "block", Material.ROCK);
	public static final Block MAGENTA_TETRIS_BLOCK = new BlockTetris("magenta", "block", Material.ROCK);
	public static final Block PURPLE_TETRIS_BLOCK = new BlockTetris("purple", "block", Material.ROCK);
	public static final Block BROWN_TETRIS_BLOCK = new BlockTetris("brown", "block", Material.ROCK);
	public static final Block WHITE_TETRIS_BLOCK = new BlockTetris("white", "block", Material.ROCK);
	public static final Block LIGHT_GRAY_TETRIS_BLOCK = new BlockTetris("light_gray", "block", Material.ROCK);
	public static final Block GRAY_TETRIS_BLOCK = new BlockTetris("gray", "block", Material.ROCK);
	public static final Block BLACK_TETRIS_BLOCK = new BlockTetris("black", "block", Material.ROCK);
	public static final Block TETRIS_GLASS = new BlockFallingGlass("tetris_glass", CreativeTabInit.TETRIS);
	public static final Block JAPANESE_TETRIS_CUSHION = new BlockTetris("japanese", "cushion", Material.CLOTH);
	public static final Block RAINBOW_TETRIS_SCAFFOLDING = new BlockTetris("rainbow", "scaffolding", Material.IRON);
	public static final Block MONOCHROME_TETRIS_SCAFFOLDING = new BlockTetris("monochrome", "scaffolding", Material.IRON);
	public static final Block VAMPIRE_STONE = new BlockBase("vampire_stone", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block MEDUSA_STONE = new BlockBase("medusa_stone", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block MEDUSA_BRICKS = new BlockBase("medusa_bricks", CreativeTabInit.CASTLEVANIA, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block MEDUSA_BRICKS_STAIRS = new BlockStairs("medusa_brick", CreativeTabInit.CASTLEVANIA, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block BLUE_CANDY_CANE_PILLAR = new BlockPillar("blue_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block LIGHT_BLUE_CANDY_CANE_PILLAR = new BlockPillar("light_blue_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block CYAN_CANDY_CANE_PILLAR = new BlockPillar("cyan_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block GREEN_CANDY_CANE_PILLAR = new BlockPillar("green_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block LIME_CANDY_CANE_PILLAR = new BlockPillar("lime_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block YELLOW_CANDY_CANE_PILLAR = new BlockPillar("yellow_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block ORANGE_CANDY_CANE_PILLAR = new BlockPillar("orange_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block RED_CANDY_CANE_PILLAR = new BlockPillar("red_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block PINK_CANDY_CANE_PILLAR = new BlockPillar("pink_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block MAGENTA_CANDY_CANE_PILLAR = new BlockPillar("magenta_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block PURPLE_CANDY_CANE_PILLAR = new BlockPillar("purple_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block BROWN_CANDY_CANE_PILLAR = new BlockPillar("brown_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block WHITE_CANDY_CANE_PILLAR = new BlockPillar("white_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block LIGHT_GRAY_CANDY_CANE_PILLAR = new BlockPillar("light_gray_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block GRAY_CANE_PILLAR = new BlockPillar("gray_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block BLACK_CANDY_CANE_PILLAR = new BlockPillar("black_candy_cane_pillar", CreativeTabInit.CASTLEVANIA, Material.ROCK, 1.2f, 15f, SoundType.SNOW);
	public static final Block GREEN_HILL_GRASS_BLOCK = new BlockGrass("green_hill_grass_block", CreativeTabInit.SONIC, Material.GROUND, 0.6f, 3f, SoundType.PLANT);
	public static final Block GREEN_HILL_DIRT = new BlockDirt("green_hill_dirt", CreativeTabInit.SONIC, Material.GROUND, 0.5f, 2.5f, SoundType.GROUND);
	public static final Block MARBLE_ZONE_STONE = new BlockBase("marble_zone_stone", CreativeTabInit.SONIC, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block YELLOW_STUDIOPOLIS_CLAPPER = new BlockDirectional("yellow_studiopolis_clapper", CreativeTabInit.SONIC, Material.IRON, 5f, 30f, SoundType.METAL);
	public static final Block BLUE_STUDIOPOLIS_CLAPPER = new BlockDirectional("blue_studiopolis_clapper", CreativeTabInit.SONIC, Material.IRON, 5f, 30f, SoundType.METAL);
	public static final Block SCARLET_GRASS_BLOCK = new BlockGrass("scarlet_grass_block", CreativeTabInit.UNDERTALE_DELTARUNE, Material.GROUND, 0.6f, 3f, SoundType.PLANT);
	public static final Block SCARLET_GRASS = new BlockGrassPlant("scarlet_grass", CreativeTabInit.UNDERTALE_DELTARUNE);
	public static final Block SCARLET_MUSHROOM = new BlockMushroom("scarlet", CreativeTabInit.UNDERTALE_DELTARUNE, 7);
	public static final Block SCARLET_ORCHID = new BlockFlower("scarlet_orchid", CreativeTabInit.UNDERTALE_DELTARUNE, 7);
	public static final Block IRON_SCAFFOLDING = new BlockBase("iron_scaffolding", CreativeTabInit.CELESTE, Material.IRON, 5f, 30f, SoundType.METAL);
	public static final Block PURPLE_BRICKS = new BlockBase("purple_bricks", CreativeTabInit.CELESTE, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block PURPLE_BRICKS_STAIRS = new BlockStairs("purple_brick", CreativeTabInit.CELESTE, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block CYAN_BRICKS = new BlockBase("cyan_bricks", CreativeTabInit.CELESTE, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block CYAN_BRICKS_STAIRS = new BlockStairs("cyan_brick", CreativeTabInit.CELESTE, Material.ROCK, 2f, 30f, SoundType.STONE);
	public static final Block ELDER_PEBBLES = new BlockBase("elder_pebbles", CreativeTabInit.CELESTE, Material.ROCK, 2f, 30f, SoundType.STONE, 5);
	public static final Block SPACE_MATTER = new BlockBase("space_matter", CreativeTabInit.CELESTE, Material.SAND, 0.4f, 30f, SoundTypeInit.SPACE_MATTER, 5);
	public static final Block SPACE_OBSIDIAN = new BlockBase("space_obsidian", CreativeTabInit.CELESTE, Material.ROCK, -1f, 6000000.0f, SoundType.STONE, 2);
	public static final Block REWIND_BLOCK = new BlockUnstable("rewind_block", CreativeTabInit.YOUTUBE, Material.IRON, 5f, 30f, SoundType.METAL);
	public static final Block KORETATO_BLOCK = new BlockDirectional("koretato_block", CreativeTabInit.YOUTUBE, Material.GROUND, 0.4f, 10f, SoundType.SNOW);
	public static final Block BLUE_BALLOON = new BlockBalloon("blue");
	public static final Block LIGHT_BLUE_BALLOON = new BlockBalloon("light_blue");
	public static final Block CYAN_BALLOON = new BlockBalloon("cyan");
	public static final Block GREEN_BALLOON = new BlockBalloon("green");
	public static final Block LIME_BALLOON = new BlockBalloon("lime");
	public static final Block YELLOW_BALLOON = new BlockBalloon("yellow");
	public static final Block ORANGE_BALLOON = new BlockBalloon("orange");
	public static final Block RED_BALLOON = new BlockBalloon("red");
	public static final Block PINK_BALLOON = new BlockBalloon("pink");
	public static final Block MAGENTA_BALLOON = new BlockBalloon("magenta");
	public static final Block PURPLE_BALLOON = new BlockBalloon("purple");
	public static final Block BROWN_BALLOON = new BlockBalloon("brown");
	public static final Block WHITE_BALLOON = new BlockBalloon("white");
	public static final Block LIGHT_GRAY_BALLOON = new BlockBalloon("light_gray");
	public static final Block GRAY_BALLOON = new BlockBalloon("gray");
	public static final Block BLACK_BALLOON = new BlockBalloon("black");
	public static final Block BLUE_PUYO = new BlockPuyo("blue", CreativeTabInit.PUYO_PUYO, Material.CLAY, 0f, 0f, SoundType.SLIME);
	public static final Block TURQUOISE_PUYO = new BlockPuyo("turquoise", CreativeTabInit.PUYO_PUYO, Material.CLAY, 0f, 0f, SoundType.SLIME);
	public static final Block GREEN_PUYO = new BlockPuyo("green", CreativeTabInit.PUYO_PUYO, Material.CLAY, 0f, 0f, SoundType.SLIME);
	public static final Block YELLOW_PUYO = new BlockPuyo("yellow", CreativeTabInit.PUYO_PUYO, Material.CLAY, 0f, 0f, SoundType.SLIME);
	public static final Block RED_PUYO = new BlockPuyo("red", CreativeTabInit.PUYO_PUYO, Material.CLAY, 0f, 0f, SoundType.SLIME);
	public static final Block PURPLE_PUYO = new BlockPuyo("purple", CreativeTabInit.PUYO_PUYO, Material.CLAY, 0f, 0f, SoundType.SLIME);
	public static final Block GARBAGE_PUYO = new BlockDirectional("garbage_puyo", CreativeTabInit.PUYO_PUYO, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block POINT_PUYO = new BlockDirectional("point_puyo", CreativeTabInit.PUYO_PUYO, Material.ROCK, 1.5f, 30f, SoundType.STONE, 10);
	public static final Block HARD_PUYO = new BlockDirectional("hard_puyo", CreativeTabInit.PUYO_PUYO, Material.ROCK, 1.5f, 30f, SoundType.STONE);
	public static final Block IRON_PUYO = new BlockDirectional("iron_puyo", CreativeTabInit.PUYO_PUYO, Material.IRON, 5f, 30f, SoundType.METAL);
	public static final Block PUYO_BLOCK = new BlockBase("puyo_block", CreativeTabInit.PUYO_PUYO, Material.ROCK, 1.5f, 30f, SoundType.STONE);
}
