package com.hugman.mubble.init;

import com.hugman.dawn.api.creator.SoundCreator;
import net.minecraft.sound.SoundEvent;

public class MubbleSounds extends MubblePack {
	public static final SoundEvent BLOCK_PRESENT_CLOSE = register(new SoundCreator.Builder("block.present.close"));
	public static final SoundEvent BLOCK_PRESENT_OPEN = register(new SoundCreator.Builder("block.present.open"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_CHANGE_LOOT = register(new SoundCreator.Builder("block.lootable_punch_block.change_loot"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_SMB = register(new SoundCreator.Builder("block.lootable_punch_block.loot.smb"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_SMB3 = register(new SoundCreator.Builder("block.lootable_punch_block.loot.smb3"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_SMW = register(new SoundCreator.Builder("block.lootable_punch_block.loot.smw"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_NSMBU = register(new SoundCreator.Builder("block.lootable_punch_block.loot.nsmbu"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_COIN_SMB = register(new SoundCreator.Builder("block.lootable_punch_block.loot.coin.smb"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_COIN_SMB3 = register(new SoundCreator.Builder("block.lootable_punch_block.loot.coin.smb3"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_COIN_SMW = register(new SoundCreator.Builder("block.lootable_punch_block.loot.coin.smw"));
	public static final SoundEvent BLOCK_LOOTABLE_PUNCH_BLOCK_LOOT_COIN_NSMBU = register(new SoundCreator.Builder("block.lootable_punch_block.loot.coin.nsmbu"));
	public static final SoundEvent BLOCK_BRICK_BLOCK_BREAK_SMB = register(new SoundCreator.Builder("block.brick_block.break.smb"));
	public static final SoundEvent BLOCK_BRICK_BLOCK_BREAK_SMB3 = register(new SoundCreator.Builder("block.brick_block.break.smb3"));
	public static final SoundEvent BLOCK_BRICK_BLOCK_BREAK_SMW = register(new SoundCreator.Builder("block.brick_block.break.smw"));
	public static final SoundEvent BLOCK_BRICK_BLOCK_BREAK_NSMBU = register(new SoundCreator.Builder("block.brick_block.break.nsmbu"));
	public static final SoundEvent BLOCK_EMPTY_BLOCK_HIT_SMB = register(new SoundCreator.Builder("block.empty_block.hit.smb"));
	public static final SoundEvent BLOCK_EMPTY_BLOCK_HIT_SMB3 = register(new SoundCreator.Builder("block.empty_block.hit.smb3"));
	public static final SoundEvent BLOCK_EMPTY_BLOCK_HIT_SMW = register(new SoundCreator.Builder("block.empty_block.hit.smw"));
	public static final SoundEvent BLOCK_EMPTY_BLOCK_HIT_NSMBU = register(new SoundCreator.Builder("block.empty_block.hit.nsmbu"));
	public static final SoundEvent BLOCK_NOTE_BLOCK_JUMP_SMB = register(new SoundCreator.Builder("block.note_block.jump.smb"));
	public static final SoundEvent BLOCK_NOTE_BLOCK_JUMP_SMB3 = register(new SoundCreator.Builder("block.note_block.jump.smb3"));
	public static final SoundEvent BLOCK_NOTE_BLOCK_JUMP_SMW = register(new SoundCreator.Builder("block.note_block.jump.smw"));
	public static final SoundEvent BLOCK_NOTE_BLOCK_JUMP_LOW_NSMBU = register(new SoundCreator.Builder("block.note_block.jump.low.nsmbu"));
	public static final SoundEvent BLOCK_NOTE_BLOCK_JUMP_HIGH_NSMBU = register(new SoundCreator.Builder("block.note_block.jump.high.nsmbu"));
	public static final SoundEvent BLOCK_DOOR_OPEN_SMB = register(new SoundCreator.Builder("block.door.open.smb"));
	public static final SoundEvent BLOCK_DOOR_OPEN_SMB3 = register(new SoundCreator.Builder("block.door.open.smb3"));
	public static final SoundEvent BLOCK_DOOR_OPEN_SMW = register(new SoundCreator.Builder("block.door.open.smw"));
	public static final SoundEvent BLOCK_DOOR_OPEN_NSMBU = register(new SoundCreator.Builder("block.door.open.nsmbu"));
	public static final SoundEvent BLOCK_DOOR_CLOSE_SMB = register(new SoundCreator.Builder("block.door.close.smb"));
	public static final SoundEvent BLOCK_DOOR_CLOSE_SMB3 = register(new SoundCreator.Builder("block.door.close.smb3"));
	public static final SoundEvent BLOCK_DOOR_CLOSE_SMW = register(new SoundCreator.Builder("block.door.close.smw"));
	public static final SoundEvent BLOCK_DOOR_CLOSE_NSMBU = register(new SoundCreator.Builder("block.door.close.nsmbu"));
	public static final SoundEvent BLOCK_DOOR_KEY_SUCCESS_SMB = register(new SoundCreator.Builder("block.door.key.success.smb"));
	public static final SoundEvent BLOCK_DOOR_KEY_SUCCESS_SMB3 = register(new SoundCreator.Builder("block.door.key.success.smb3"));
	public static final SoundEvent BLOCK_DOOR_KEY_SUCCESS_SMW = register(new SoundCreator.Builder("block.door.key.success.smw"));
	public static final SoundEvent BLOCK_DOOR_KEY_SUCCESS_NSMBU = register(new SoundCreator.Builder("block.door.key.success.nsmbu"));
	public static final SoundEvent BLOCK_DOOR_KEY_FAIL_SMB = register(new SoundCreator.Builder("block.door.key.fail.smb"));
	public static final SoundEvent BLOCK_DOOR_KEY_FAIL_SMB3 = register(new SoundCreator.Builder("block.door.key.fail.smb3"));
	public static final SoundEvent BLOCK_DOOR_KEY_FAIL_SMW = register(new SoundCreator.Builder("block.door.key.fail.smw"));
	public static final SoundEvent BLOCK_DOOR_KEY_FAIL_NSMBU = register(new SoundCreator.Builder("block.door.key.fail.nsmbu"));
	public static final SoundEvent BLOCK_DREAM_BLOCK_BREAK = register(new SoundCreator.Builder("block.dream_block.break"));
	public static final SoundEvent BLOCK_DREAM_BLOCK_FALL = register(new SoundCreator.Builder("block.dream_block.fall"));
	public static final SoundEvent BLOCK_DREAM_BLOCK_PLACE = register(new SoundCreator.Builder("block.dream_block.place"));
	public static final SoundEvent BLOCK_DREAM_BLOCK_HIT = register(new SoundCreator.Builder("block.dream_block.hit"));
	public static final SoundEvent BLOCK_DREAM_BLOCK_STEP = register(new SoundCreator.Builder("block.dream_block.step"));
	public static final SoundEvent BLOCK_SPRING_TRIGGER = register(new SoundCreator.Builder("block.spring.trigger"));
	public static final SoundEvent ITEM_CAPE_FEATHER_USE = register(new SoundCreator.Builder("item.cape_feather.use"));
	public static final SoundEvent ITEM_JINGLE_BELLS_USE = register(new SoundCreator.Builder("item.jingle_bells.use"));
	public static final SoundEvent ITEM_SMASH_BALL_USE = register(new SoundCreator.Builder("item.smash_ball.use"));
	public static final SoundEvent ITEM_SUPER_MUSHROOM_CONSUME = register(new SoundCreator.Builder("item.super_mushroom.consume"));
	public static final SoundEvent ITEM_SUPER_STAR_THEME = register(new SoundCreator.Builder("item.super_star.theme"));
	public static final SoundEvent ITEM_LIGHTSABER_BLOCK = register(new SoundCreator.Builder("item.lightsaber.block"));
	public static final SoundEvent ITEM_LIGHTSABER_HIT = register(new SoundCreator.Builder("item.lightsaber.hit"));
	public static final SoundEvent ITEM_LIGHTSABER_IDLE = register(new SoundCreator.Builder("item.lightsaber.idle"));
	public static final SoundEvent ITEM_LIGHTSABER_PULL_IN = register(new SoundCreator.Builder("item.lightsaber.pull_in"));
	public static final SoundEvent ITEM_LIGHTSABER_PULL_OUT = register(new SoundCreator.Builder("item.lightsaber.pull_out"));
	public static final SoundEvent ITEM_LIGHTSABER_SPARK = register(new SoundCreator.Builder("item.lightsaber.spark"));
	public static final SoundEvent ITEM_LIGHTSABER_SWIPE = register(new SoundCreator.Builder("item.lightsaber.swipe"));
	public static final SoundEvent ITEM_LIGHTSABER_THROW_FAR = register(new SoundCreator.Builder("item.lightsaber.throw.far"));
	public static final SoundEvent ITEM_LIGHTSABER_THROW_NEAR = register(new SoundCreator.Builder("item.lightsaber.throw.near"));
	public static final SoundEvent COSTUME_CAPPY_AMBIENT = register(new SoundCreator.Builder("costume.cappy.ambient"));
	public static final SoundEvent COSTUME_CAPPY_AMBIENT_NETHER = register(new SoundCreator.Builder("costume.cappy.ambient.nether"));
	public static final SoundEvent COSTUME_CAPPY_EQUIP = register(new SoundCreator.Builder("costume.cappy.equip"));
	public static final SoundEvent COSTUME_CAPPY_HAPPY = register(new SoundCreator.Builder("costume.cappy.happy"));
	public static final SoundEvent COSTUME_CAPPY_HELP = register(new SoundCreator.Builder("costume.cappy.help"));
	public static final SoundEvent COSTUME_CAPPY_HELP_WATER = register(new SoundCreator.Builder("costume.cappy.help.water"));
	public static final SoundEvent COSTUME_PROPELLER_BOX_USE = register(new SoundCreator.Builder("costume.propeller_box.use"));
	public static final SoundEvent COSTUME_PROPELLER_BOX_FALL = register(new SoundCreator.Builder("costume.propeller_box.fall"));
	public static final SoundEvent ENTITY_CHINCHO_AMBIENT = register(new SoundCreator.Builder("entity.chincho.ambient"));
	public static final SoundEvent ENTITY_CHINCHO_HURT = register(new SoundCreator.Builder("entity.chincho.hurt"));
	public static final SoundEvent ENTITY_CHINCHO_DEATH = register(new SoundCreator.Builder("entity.chincho.death"));
	public static final SoundEvent ENTITY_FIREBALL_HIT_BLOCK = register(new SoundCreator.Builder("entity.fireball.hit.block"));
	public static final SoundEvent ENTITY_FIREBALL_HIT_ENTITY = register(new SoundCreator.Builder("entity.fireball.hit.entity"));
	public static final SoundEvent ENTITY_FIREBALL_HIT_MELTABLE = register(new SoundCreator.Builder("entity.fireball.hit.meltable"));
	public static final SoundEvent ENTITY_FIREBALL_THROW = register(new SoundCreator.Builder("entity.fireball.throw"));
	public static final SoundEvent ENTITY_ICEBALL_HIT_BLOCK = register(new SoundCreator.Builder("entity.iceball.hit.block"));
	public static final SoundEvent ENTITY_ICEBALL_HIT_ENTITY = register(new SoundCreator.Builder("entity.iceball.hit.entity"));
	public static final SoundEvent ENTITY_ICEBALL_THROW = register(new SoundCreator.Builder("entity.iceball.throw"));
	public static final SoundEvent ENTITY_KIRBY_BALL_HIT_BLOCK = register(new SoundCreator.Builder("entity.kirby_ball.hit.block"));
	public static final SoundEvent ENTITY_KIRBY_BALL_HIT_ENTITY = register(new SoundCreator.Builder("entity.kirby_ball.hit.entity"));
	public static final SoundEvent ENTITY_KIRBY_BALL_REBOUND = register(new SoundCreator.Builder("entity.kirby_ball.rebound"));
	public static final SoundEvent ENTITY_KIRBY_BALL_THROW = register(new SoundCreator.Builder("entity.kirby_ball.throw"));
	public static final SoundEvent ENTITY_TOAD_AMBIENT = register(new SoundCreator.Builder("entity.toad.ambient"));
	public static final SoundEvent ENTITY_TOAD_BUP = register(new SoundCreator.Builder("entity.toad.bup"));
	public static final SoundEvent ENTITY_TOAD_NO = register(new SoundCreator.Builder("entity.toad.no"));
	public static final SoundEvent ENTITY_TOAD_TRADE = register(new SoundCreator.Builder("entity.toad.trade"));
	public static final SoundEvent ENTITY_TOAD_YES = register(new SoundCreator.Builder("entity.toad.yes"));
	public static final SoundEvent ENTITY_TOAD_HURT = register(new SoundCreator.Builder("entity.toad.hurt"));
	public static final SoundEvent ENTITY_TOAD_DEATH = register(new SoundCreator.Builder("entity.toad.death"));
	public static final SoundEvent ENTITY_GOOMBA_STEP = register(new SoundCreator.Builder("entity.goomba.step"));
	public static final SoundEvent ENTITY_GOOMBA_CRUSH = register(new SoundCreator.Builder("entity.goomba.crush"));
	public static final SoundEvent ENTITY_GOOMBA_HURT = register(new SoundCreator.Builder("entity.goomba.hurt"));
	public static final SoundEvent ENTITY_GOOMBA_DEATH = register(new SoundCreator.Builder("entity.goomba.death"));
	public static final SoundEvent ENTITY_PUFFERFISH_AEUGH = register(new SoundCreator.Builder("entity.pufferfish.aeugh"));
	public static final SoundEvent UI_TIMESWAP_TABLE_TAKE_RESULT = register(new SoundCreator.Builder("ui.timeswap_table.take_result"));

	public static void init() {

	}
}